# Generated by Django 4.0.4 on 2022-04-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres del autor: ')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos del autor: ')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook: ')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram: ')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter: ')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web: ')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico: ')),
                ('estado', models.BooleanField(default=True, verbose_name='Autor activo/Autor no activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creción: ')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la categoría: ')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoráa activada/Categoría no activada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación:')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
    ]
