# Generated by Django 4.0.4 on 2022-04-26 01:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import noticias.models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=90, verbose_name='Título: ')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug: ')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('descripcion', models.CharField(max_length=110, verbose_name='Descripción: ')),
                ('imagen', models.URLField(max_length=255)),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('fecha_creacio', models.DateField(auto_now_add=True, verbose_name='Fecha de creación ')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.autor')),
                ('categoria', models.ForeignKey(on_delete=noticias.models.Categoria, to='noticias.categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
